//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YachtLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schiff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schiff()
        {
            this.Toerns = new HashSet<Toern>();
        }
    
        public int Id { get; set; }
        public int EignerId { get; set; }
        public int BasisId { get; set; }
        public int PersonId1 { get; set; }
        public string Typ { get; set; }
        public short Laenge { get; set; }
        public short Baujahr { get; set; }
        public string Schiffsname { get; set; }
    
        public virtual Basis Basis { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Toern> Toerns { get; set; }
    }
}
